### ISSUE TITLE
ckeditor5 dropdown padding

### ISSUE THREAD

**Issue by leevigraham** [craftcms/ckeditor#58]
### Description

`readable` class adds extra padding to dropdowns. `readable` should only be applied to `.ck-content`

![Screenshot 2023-01-31 at 3 05 40 pm](https://user-images.githubusercontent.com/25124/215660736-b7077990-03cd-4a33-b14d-cac2cc956540.png)

**Comment by leevigraham** [comment]
Maybe applying the readable styles directly to `.ck-content`:

```css
@charset "UTF-8";
@import '../../../../node_modules/craftcms-sass/mixins';

.ck.ck-editor__editable:not(.ck-editor__nested-editable).ck-content.ck-editor__editable_inline {
  @include input-styles;
  padding: 20px;
  &.ck-focused {
    @include input-focused-styles;
  }
}

.ck.ck-content {
  @include readable;
}
```
